### ISSUE TITLE
Updating the Hue/Saturation/Lightness/Luminance options doesn't update sample code

### ISSUE THREAD

**Issue by jacksleight** [SimeonGriggs/tints.dev#40]
Thanks for this awesome tool!

I've just noticed that when you update any of the Hue/Saturation/Lightness fields or the Luminance/Lightness toggle the sample code under `Paste this into your tailwind.config.js` doesn't update. It only seems to update when you edit the source swatch value.

**Comment by SimeonGriggs** [comment]
Good catch! Fixed in #41 :)
